# Generated by Django 5.2.8 on 2025-11-19 12:12

from django.db import migrations, connection


def convert_dates_to_datetime(apps, schema_editor):
    """기존 DateField 데이터를 DateTimeField 형식으로 변환"""
    # SQLite에서 직접 SQL을 사용하여 날짜 문자열을 datetime으로 변환
    with connection.cursor() as cursor:
        # tweets_tweet 테이블 업데이트
        cursor.execute("""
            UPDATE tweets_tweet 
            SET created_at = datetime(created_at || ' 00:00:00')
            WHERE typeof(created_at) = 'text' AND length(created_at) = 10
        """)
        cursor.execute("""
            UPDATE tweets_tweet 
            SET updated_at = datetime(updated_at || ' 00:00:00')
            WHERE typeof(updated_at) = 'text' AND length(updated_at) = 10
        """)
        
        # tweets_like 테이블 업데이트
        cursor.execute("""
            UPDATE tweets_like 
            SET created_at = datetime(created_at || ' 00:00:00')
            WHERE typeof(created_at) = 'text' AND length(created_at) = 10
        """)
        cursor.execute("""
            UPDATE tweets_like 
            SET updated_at = datetime(updated_at || ' 00:00:00')
            WHERE typeof(updated_at) = 'text' AND length(updated_at) = 10
        """)


def reverse_migration(apps, schema_editor):
    """역방향 마이그레이션 (필요시)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_like_created_at_alter_like_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_dates_to_datetime, reverse_migration),
    ]
